plugins {
    id("java")
    id("war")
}

group = "ru.dadyDobro"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

def springVersion = '7.0.8'
def springDataJpaVersion = '4.0.5'
def springThymeLeafVersion = '3.1.5.RELEASE'
def lombokVersion = '1.18.46'
def mapstructVersion = '1.5.5.Final'
def flywayVersion = '12.10.0'
def hibernateCoreVersion = '6.4.10.Final'
def hibernateValidatorVersion = '8.0.2.Final'
def jakartaValidationVersion = '3.0.2'
def jacksonDatabindVersion = '3.2.0'
def jakartaServletVersion = '6.1.0'
def postgresSqlVersion = '42.7.11'

dependencies {
    implementation "org.springframework:spring-orm:${springVersion}"
    implementation "org.springframework:spring-webmvc:${springVersion}"
    implementation "org.springframework.data:spring-data-jpa:${springDataJpaVersion}"
    implementation "org.thymeleaf:thymeleaf-spring6:${springThymeLeafVersion}"
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    implementation "org.hibernate.orm:hibernate-core:${hibernateCoreVersion}"
    implementation "org.hibernate.validator:hibernate-validator:${hibernateValidatorVersion}"
    implementation "jakarta.validation:jakarta.validation-api:${jakartaValidationVersion}"
    implementation "tools.jackson.core:jackson-databind:${jacksonDatabindVersion}"
    implementation "org.flywaydb:flyway-core:${flywayVersion}"
    implementation "org.flywaydb:flyway-database-postgresql:${flywayVersion}"

    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    compileOnly "jakarta.servlet:jakarta.servlet-api:${jakartaServletVersion}"

    runtimeOnly "org.postgresql:postgresql:${postgresSqlVersion}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

task prepareKotlinBuildScriptModel {
}

apply plugin: 'idea'
