CREATE TABLE Locations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(100)                            NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    latitude  DECIMAL(10, 5)                          NOT NULL,
    longitude DECIMAL(10, 5)                          NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE Sessions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

CREATE TABLE Users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(100)                            NOT NULL,
    password VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE UNIQUE INDEX user_login_index ON Users (login);

ALTER TABLE Locations
    ADD CONSTRAINT FK_LOCATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES Users (id);

ALTER TABLE Sessions
    ADD CONSTRAINT FK_SESSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES Users (id);